title: 현경이의 삽질기록
email: khc0275@naver.com
description: |
  삽질 2년차, 구글링 박사가 되었다
baseurl: ''
url: 'http://hyunkyung12.github.io'
timezone: Asia/Seoul 

repository: hyunkyung12/hyunkyung12.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: khc0275@naver.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
# google_analytics:
#   ua: 'UA-72007721-1'
# facebook:
#   app_id: '1204347326263800'
#   username: nkakao
# twitter:
#   username: kakaodev
# google_plus:
#   username: kakaodev
github_url:
  username: hyunkyung12
